version: 3.1
services:
  app:

  api:

  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: 
        MONGO_INITDB_ROOT_USERNAME: 
  db-gui:
    image: mongo-express
